<?php
define("DATABASE_HOST", "{HOST DO BANCO}");
define("DATABASE_PORT", "{PORTA DE ACESSO AO BANCO}");
define("DATABASE_DBNAME", "{NOME DO BANCO DE DADOS}");
define("DATABASE_USER", "{NOME DO USUÁRIO DO BANCO DE DADOS}");
define("DATABASE_PASSWORD", "{SENHA DO USUÁRIO DO BANCO DE DADOS}");